--.........................................................................
--SQL script for post deployment configuration of load control
--Project: IAE tutorials
--Layer: Raw Vault
--.........................................................................
USE [{loadcontrol#loadcontrol#database_name}];
GO


--.........................................................................
--Prepare registration of load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[Build_LoadConfig] @LoadConfig = N'IAE tutorials', @ModelObjectLayer = N'Raw Vault';

--.........................................................................
--Register load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'CreditCard_Hub',                       @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_CreditCard_Hub_Loader',        @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'CreditCard_Satellite',                 @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_CreditCard_Satellite_Loader',  @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Currency_Reference_Table',             @ModelObjectPart = N'Reference Table Loader',               @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Reference Table',                      @LoadObject = N'RDV_ReferenceTable_Currency_Reference_Table_Loader', @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'CurrencyRate_Hub',                     @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_CurrencyRate_Hub_Loader',      @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'CurrencyRate_Satellite',               @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_CurrencyRate_Satellite_Loader', @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Customer_Hub',                         @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_Customer_Hub_Loader',          @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Customer_Satellite',                   @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_Customer_Satellite_Loader',    @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_CreditCard',                     @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Link',                                 @LoadObject = N'RDV_LNK_Order_CreditCard_Loader',      @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_CurrencyRate',                   @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Link',                                 @LoadObject = N'RDV_LNK_Order_CurrencyRate_Loader',    @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_Customer',                       @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Link',                                 @LoadObject = N'RDV_LNK_Order_Customer_Loader',        @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_Hub',                            @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_Order_Hub_Loader',             @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_OrderDetail',                    @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Link',                                 @LoadObject = N'RDV_LNK_Order_OrderDetail_Loader',     @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_Satellite',                      @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_Order_Satellite_Loader',       @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'OrderDetail_Hub',                      @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_OrderDetail_Hub_Loader',       @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'OrderDetail_Satellite',                @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_OrderDetail_Satellite_Loader', @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Time_Reference_Table',                 @ModelObjectPart = N'Reference Table Loader',               @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Reference Table',                      @LoadObject = N'RDV_ReferenceTable_Time_Reference_Table_Loader', @SchemaName = N'{iaetutorials#rawvault#schema_name}', @DatabaseName = N'{iaetutorials#rawvault#database_name}', @ServerName = N'{iaetutorials#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;

--.........................................................................
--Register load object dependencies
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'CreditCard_Hub',                       @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'CreditCard',                           @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'CreditCard_Satellite',                 @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'CreditCard',                           @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Currency_Reference_Table',             @ModelObjectPart = N'Reference Table Loader',               @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Currency',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'CurrencyRate_Hub',                     @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'CurrencyRate',                         @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'CurrencyRate_Satellite',               @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'CurrencyRate',                         @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Customer_Hub',                         @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Customer_Satellite',                   @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_CreditCard',                     @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'CreditCard',                           @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_CreditCard',                     @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Order',                                @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_CurrencyRate',                   @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'CurrencyRate',                         @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_CurrencyRate',                   @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Order',                                @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_Customer',                       @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_Customer',                       @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Order',                                @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_Hub',                            @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Order',                                @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_OrderDetail',                    @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Order',                                @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_OrderDetail',                    @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'OrderDetail',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Order_Satellite',                      @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Order',                                @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'OrderDetail_Hub',                      @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'OrderDetail',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'OrderDetail_Satellite',                @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'OrderDetail',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'IAE tutorials',                        @ModelObject = N'Time_Reference_Table',                 @ModelObjectPart = N'Reference Table Loader',               @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'IAE tutorials',                        @DependentOnModelObject = N'Time',                                 @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;

GO
