id: '6e7edf08-2b04-44cc-09c6-08dbbe9037fc'
version: 'v1.1'
name: 'IAE tutorials'
description: 'IAE tutorials'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Mssql'
  version: '1.2.0-rc02'
sourceSystems:
  - id: '7b2816d0-f705-4df0-8ddd-20ba9117ae7c'
    name: 'Source'
    description: ''
